### ISSUE TITLE
Issue on World Gen C2ME Error

### ISSUE THREAD

**Issue by suerion** [mammut53/more-babies#16]
Hey Guys, i got allways with C2ME this error:

Without More-Babies it does not log as problem anymore? Could you look on it Please :)

```[17:29:57] [c2me-worker-4/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-4)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 

java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-4)
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fixes-worldgen-threading-is0.206+1.21.1-8e6132e13de37f5.jar:?]
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fixes-worldgen-threading-is0.206+1.21.1-8e6132e13de37f5.jar:?]
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:86) ~[c2me-fixes-worldgen-threading-is0.206+1.21.1-8e6132e13de37f5.jar:?]
	at net.minecraft.class_6566.method_43057(class_6566.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_3366$class_3384.redirect$ekj000$more_babies$createElderGuardian(com/github/mammut53/more_babies/mixin/world/level/levelgen/structure/OceanMonumentPieceMixin.java [more_babies.mixins.json]:25) ~[server-intermediary.jar:?]
	at net.minecraft.class_3366$class_3384.method_14772(net/minecraft/class_3366$class_3384.java:182) ~[server-intermediary.jar:?]
	at net.minecraft.class_3366$class_3383.method_14931(class_3366.java:1774) ~[server-intermediary.jar:?]
	at net.minecraft.class_3366$class_3374.method_14931(net/minecraft/class_3366$class_3374.java:444) ~[server-intermediary.jar:?]
	at net.minecraft.class_3449.mixinextras$bridge$method_14931$23(class_3449.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3449.wrapOperation$dek000$frozenlib$frozenLib$placeInChunkB(net/frozenblock/lib/worldgen/structure/mixin/StructureStartMixin.java [mixin/frozenlib.worldgen.structure.mixins.json]:121) ~[server-intermediary.jar:?]
	at net.minecraft.class_3449.method_14974(net/minecraft/class_3449.java:100) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_38265(net/minecraft/class_2794.java:324) ~[server-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:323) ~[server-intermediary.jar:?]
	at net.minecraft.class_9310.method_57610(net/minecraft/class_9310.java:103) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.mixinextras$bridge$doWork$14(class_9770.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.wrapOperation$bgc000$c2me-opts-chunk-access$runGenerationTask(com/ishland/c2me/opts/chunk_access/mixin/region_capture/MixinChunkGenerationStep.java [c2me-opts-chunk-access.mixins.json]:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.method_60560(net/minecraft/class_9770.java:33) ~[server-intermediary.jar:?]
	at com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123) ~[c2me-rewrites-chunk-system-0.3.0.206+1.21.1-efa58f5defba2ae7.jar:?]
	at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) [c2me-base-0.3.0+alpha.0.206+1.21.1-2cb0f506b64805ef.jar:?]
	at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57) [c2me-base-0.3.0+alpha.0.206+1.21.1-2cb0f506b64805ef.jar:?]
	at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) [c2me-base-0.3.0+alpha.0.206+1.21.1-2cb0f506b64805ef.jar:?]
[17:29:58] [c2me-worker-4/ERROR]: Negative index in crash report handler (0/9)
[17:29:58] [c2me-worker-4/ERROR]: Error upgrading chunk [-48, 38] to "minecraft:features"
net.minecraft.class_148: Feature placement
	at net.minecraft.class_2794.method_12102(class_2794.java:381) ~[server-intermediary.jar:?]
	at net.minecraft.class_9310.method_57610(class_9310.java:103) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.mixinextras$bridge$doWork$14(class_9770.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.wrapOperation$bgc000$c2me-opts-chunk-access$runGenerationTask(class_9770.java:526) ~[server-intermediary.jar:?]
	at net.minecraft.class_9770.method_60560(class_9770.java:33) ~[server-intermediary.jar:?]
	at com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123) ~[c2me-rewrites-chunk-system-0.3.0.206+1.21.1-efa58f5defba2ae7.jar:?]
	at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) [c2me-base-0.3.0+alpha.0.206+1.21.1-2cb0f506b64805ef.jar:?]
	at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57) [c2me-base-0.3.0+alpha.0.206+1.21.1-2cb0f506b64805ef.jar:?]
	at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) [c2me-base-0.3.0+alpha.0.206+1.21.1-2cb0f506b64805ef.jar:?]
Caused by: com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom$1: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-4)
```

**Comment by suerion** [comment]
Here the Log file:

[latest.log](https://github.com/user-attachments/files/16996248/latest.log)
